// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx7cG0xYB0NGGlQUoCbPMYUey5FIn15sw',
    appId: '1:157515850596:web:25c70dbfa465bdba6c5071',
    messagingSenderId: '157515850596',
    projectId: 'dalel-8a557',
    authDomain: 'dalel-8a557.firebaseapp.com',
    storageBucket: 'dalel-8a557.appspot.com',
    measurementId: 'G-18XKL9TSE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgd6TmBS93QUtG-kN7n8jltajvs4Fyjos',
    appId: '1:157515850596:android:c039509b1e5032776c5071',
    messagingSenderId: '157515850596',
    projectId: 'dalel-8a557',
    storageBucket: 'dalel-8a557.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPKZGj3S21nJJuOy8eUumysNh1ndc3wbI',
    appId: '1:157515850596:ios:2ffa451cbd200bd46c5071',
    messagingSenderId: '157515850596',
    projectId: 'dalel-8a557',
    storageBucket: 'dalel-8a557.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPKZGj3S21nJJuOy8eUumysNh1ndc3wbI',
    appId: '1:157515850596:ios:2ffa451cbd200bd46c5071',
    messagingSenderId: '157515850596',
    projectId: 'dalel-8a557',
    storageBucket: 'dalel-8a557.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx7cG0xYB0NGGlQUoCbPMYUey5FIn15sw',
    appId: '1:157515850596:web:7d4e09886757dc896c5071',
    messagingSenderId: '157515850596',
    projectId: 'dalel-8a557',
    authDomain: 'dalel-8a557.firebaseapp.com',
    storageBucket: 'dalel-8a557.appspot.com',
    measurementId: 'G-CE23J565XN',
  );
}
